name: Ubuntu

on:
  push:
    branches:
      - develop
      - master
      - release/*
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: ghcr.io/nlohmann/json-ci:v1.0.0
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "ğŸ” Branch name is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Clone nlohmann json
        uses: actions/checkout@master
        with:
          repository: nlohmann/json
          path: nlohmann-json
          ref: release/3.10.2
      - name: Build and install nlohmann json
        run: |
          cd nlohmann-json
          cmake -S . -DJSON_VALIDATOR_BUILD_EXAMPLES=ON -DJSON_VALIDATOR_BUILD_TESTS=ON -B build
          cmake --build build --target install -j$(nproc)
          cd ..
      - name: Clone json-schema-validator
        uses: actions/checkout@v2
      - name: cmake
        run: cmake -S . -B build
      - name: build
        run: cmake --build build --target all -j$(nproc)
      - name: test
        run: cd build && ctest
  build_and_test_stand_alone:
    runs-on: ubuntu-latest
    container: ghcr.io/nlohmann/json-ci:v1.0.0
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "ğŸ” Branch name is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Clone json-schema-validator
        uses: actions/checkout@v2
      - name: Cmake
        run: cmake -S . -DJSON_VALIDATOR_BUILD_EXAMPLES=ON -DJSON_VALIDATOR_BUILD_TESTS=ON -B build
      - name: Build
        run: cmake --build build --target all -j$(nproc)
      - name: Test
        run: cd build && ctest
      - name: Publish Test
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/Testing/**/Test.xml
